//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogSiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Görseller
    {
        public int GörselID { get; set; }
        public string GörselBaslık { get; set; }
        public string Görsel { get; set; }
        public Nullable<System.DateTime> GörselYayınlanmaTarih { get; set; }
    }
}
